version: "3.9"
services:
  findadev-db:
    image: postgres
    restart: always
    container_name: findadev-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: elismoist
      PGDATA: /data/findadev
    volumes:
      - postgres:/data/findadev

volumes:
  postgres:
