version: "3.9"
services:
  liquidation-db:
    image: postgres
    restart: always
    container_name: liquidation-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: elismoist
      PGDATA: /data/liquidation
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
