export type TAGS = Record<"value" | "label" | "count", string>;
export const FRAMEWORKS = [
  { label: "Python", value: "Python", count: "118604" },
  { label: "Java", value: "Java", count: "82042" },
  { label: "Go", value: "Go", count: "71909" },
  { label: "JavaScript", value: "JavaScript", count: "69089" },
  { label: "C++", value: "C++", count: "66283" },
  { label: "TypeScript", value: "TypeScript", count: "51471" },
  { label: "PHP", value: "PHP", count: "39698" },
  { label: "Ruby", value: "Ruby", count: "32975" },
  { label: "C", value: "C", count: "32344" },
  { label: "C#", value: "C#", count: "24118" },
  { label: "Nix", value: "Nix", count: "19148" },
  { label: "Shell", value: "Shell", count: "16470" },
  { label: "HTML", value: "HTML", count: "14122" },
  { label: "Rust", value: "Rust", count: "13121" },
  { label: "Scala", value: "Scala", count: "11145" },
  { label: "Kotlin", value: "Kotlin", count: "10369" },
  { label: "Swift", value: "Swift", count: "7550" },
  { label: "Dart", value: "Dart", count: "4995" },
  { label: "Jupyter Notebook", value: "Jupyter Notebook", count: "4460" },
  { label: "Makefile", value: "Makefile", count: "2675" },
  { label: "Groovy", value: "Groovy", count: "2642" },
  { label: "Perl", value: "Perl", count: "2305" },
  { label: "Lua", value: "Lua", count: "2246" },
  { label: "HCL", value: "HCL", count: "2199" },
  { label: "DM", value: "DM", count: "2183" },
  { label: "SystemVerilog", value: "SystemVerilog", count: "2018" },
  { label: "CSS", value: "CSS", count: "1984" },
  { label: "Objective-C", value: "Objective-C", count: "1666" },
  { label: "Elixir", value: "Elixir", count: "1612" },
  { label: "SCSS", value: "SCSS", count: "1497" },
  { label: "Starlark", value: "Starlark", count: "1387" },
  { label: "Roff", value: "Roff", count: "1284" },
  { label: "JSON", value: "JSON", count: "1261" },
  { label: "CodeQL", value: "CodeQL", count: "1184" },
  { label: "OCaml", value: "OCaml", count: "1077" },
  { label: "Dockerfile", value: "Dockerfile", count: "1036" },
  { label: "Haskell", value: "Haskell", count: "922" },
  { label: "Vue", value: "Vue", count: "847" },
  { label: "PowerShell", value: "PowerShell", count: "836" },
  { label: "Erlang", value: "Erlang", count: "831" },
  { label: "Smarty", value: "Smarty", count: "753" },
  { label: "Emacs Lisp", value: "Emacs Lisp", count: "736" },
  { label: "Jinja", value: "Jinja", count: "725" },
  { label: "Julia", value: "Julia", count: "518" },
  { label: "Clojure", value: "Clojure", count: "507" },
  { label: "R", value: "R", count: "500" },
  { label: "CoffeeScript", value: "CoffeeScript", count: "476" },
  { label: "F#", value: "F#", count: "456" },
  { label: "Verilog", value: "Verilog", count: "452" },
  { label: "WebAssembly", value: "WebAssembly", count: "409" },
  { label: "MLIR", value: "MLIR", count: "402" },
  { label: "Adblock Filter List", value: "Adblock Filter List", count: "399" },
  { label: "Bicep", value: "Bicep", count: "341" },
  { label: "TeX", value: "TeX", count: "317" },
  { label: "XSLT", value: "XSLT", count: "292" },
  { label: "Fortran", value: "Fortran", count: "277" },
  { label: "Markdown", value: "Markdown", count: "277" },
  { label: "Cython", value: "Cython", count: "260" },
  { label: "GAP", value: "GAP", count: "255" },
  { label: "MATLAB", value: "MATLAB", count: "255" },
  { label: "Puppet", value: "Puppet", count: "253" },
  { label: "PLpgSQL", value: "PLpgSQL", count: "246" },
  { label: "Sass", value: "Sass", count: "237" },
  { label: "JetBrains MPS", value: "JetBrains MPS", count: "232" },
  { label: "Smalltalk", value: "Smalltalk", count: "219" },
  { label: "YAML", value: "YAML", count: "209" },
  { label: "BitBake", value: "BitBake", count: "206" },
  { label: "Vala", value: "Vala", count: "192" },
  { label: "Haxe", value: "Haxe", count: "187" },
  { label: "Pascal", value: "Pascal", count: "179" },
  { label: "Elm", value: "Elm", count: "163" },
  { label: "Vim Script", value: "Vim Script", count: "155" },
  { label: "Nunjucks", value: "Nunjucks", count: "148" },
  { label: "Assembly", value: "Assembly", count: "145" },
  { label: "Coq", value: "Coq", count: "143" },
  { label: "Haml", value: "Haml", count: "142" },
  { label: "ANTLR", value: "ANTLR", count: "141" },
  { label: "Gherkin", value: "Gherkin", count: "131" },
  { label: "Reason", value: "Reason", count: "127" },
  { label: "Common Lisp", value: "Common Lisp", count: "125" },
  { label: "Jsonnet", value: "Jsonnet", count: "124" },
  { label: "Standard ML", value: "Standard ML", count: "115" },
  { label: "Mathematica", value: "Mathematica", count: "108" },
  { label: "Cuda", value: "Cuda", count: "106" },
  { label: "D", value: "D", count: "105" },
  { label: "CMake", value: "CMake", count: "102" },
  { label: "GLSL", value: "GLSL", count: "99" },
  { label: "hoon", value: "hoon", count: "94" },
  { label: "Scheme", value: "Scheme", count: "89" },
  { label: "ColdFusion", value: "ColdFusion", count: "88" },
  { label: "SWIG", value: "SWIG", count: "78" },
  { label: "LLVM", value: "LLVM", count: "76" },
  { label: "Twig", value: "Twig", count: "73" },
  { label: "Nim", value: "Nim", count: "69" },
  { label: "Less", value: "Less", count: "67" },
  { label: "SaltStack", value: "SaltStack", count: "66" },
  { label: "SQF", value: "SQF", count: "62" },
  { label: "QML", value: "QML", count: "61" },
  { label: "ZAP", value: "ZAP", count: "61" },
  { label: "Tcl", value: "Tcl", count: "59" },
] satisfies TAGS[];
